#!/bin/bash

# Check if a name was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <name>"
    exit 1
fi

# Get all arguments in one string, so calling with multiple words works (ideally you'd call it with quotes)
NAME="$*"

# Convert NAME to Title Case for use in Markdown files
TITLE_NAME=$(echo "$NAME" | sed -E 's/(^|[[:space:]])([[:alpha:]])/\1\U\2/g')

# Transform the name to kebab-case:
# 1. Replace spaces with -
# 2. Make it lowercase
# 3. Remove anything that's not a letter a-z, number 0-9, or hyphen
KEBAB_NAME=$(echo "$NAME" | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')
TIMESTAMP=$(date +%s)
DIR_NAME="${TIMESTAMP}-${KEBAB_NAME}"

# Get the directory where the script is located
SCRIPT_DIR=$(dirname "$0")
TARGET_DIR="$SCRIPT_DIR/$DIR_NAME"

# If there's already a directory with the name this would use, exit without making any changes.
if [ -d "$TARGET_DIR" ]; then
    exit 0
fi

# Create the directory and the requirements.md file
mkdir -p "$TARGET_DIR"
echo "# $TITLE_NAME" > "$TARGET_DIR/requirements.md"

cat <<EOF > "$TARGET_DIR/questions.md"
# Questions about $TITLE_NAME

This file will contain questions to clarify and refine the requirements for this feature.

Any answers that start with "Suggestion:" were generated by the AI agent. If you want to accept that suggestion, remove the "Suggestion:" prefix. If you want to provide a different answer, replace the suggestion with your own answer.
EOF
